### PR TITLE
Add to documentation - Different Python Version

### PR DESCRIPTION
**Pull request by smadarasmi**
I noticed you are using urllib.requests which after doing some research is not in Python 2.7.

### CODE REVIEW

**Review by rahuldecoded — CHANGES_REQUESTED** [review]
Delete this commit. I've added it in my last commit. Thank you. 😀

**Comment by rahuldecoded** [comment]
@smadarasmi can you close this PR and update your branch and raise another PR. Otherwise merge branch master into add-to-documentation

**Comment by smadarasmi** [comment]
@rahuldecoded I have rebased it so now the only difference is this commit. Is this good?

**Comment by rahuldecoded** [comment]
LGTM 😃 Thank you.

**Review by rahuldecoded — APPROVED** [review]

**Comment by rahuldecoded** [comment]
@madar007 @smadarasmi feel free raise an issue and work on them.

**Pull request merged**
