### PR TITLE
Add google search functionality

### PR DESCRIPTION
**Pull request by 0xMoJo7**
let me know your thoughts on this

### CODE REVIEW

**Comment by rahuldecoded** [comment]
Kindly merge branch master into your branch master

**Comment by 0xMoJo7** [comment]
i dont believe i have access, if i'm understanding correctly.

"Only those with write access to this repository can merge pull requests."

**Comment by rahuldecoded** [comment]
There is a merge conflict you have to rebase.

**Comment by 0xMoJo7** [comment]
let me try that, appreciate the patience

**Comment by changhc** [comment]
You need to pull this repo, merge the conflicts and then push to your repo before making a new PR.

**Pull request closed without merging**
